/** 
 * UNIVERSIDADE FEDERAL DE SERGIPE 
 * DEPARTAMENTO DE SISTEMAS DE INFORMA??O - DSI
 * SISTEMAS DE APOIO A DECISÃO -SAD
 * PROJETAR AMBIENTE DE SUPORTE A DECISÃO BASEADO EM SISTEMA DE ACOMPANHANTES
 * ABRAÃO ALVES, IGOR BRUNO E GABRIEL SANTANA
 * 19/08/2019
 **/

USE QUEROACOMPANHANTE_SAD;

EXEC SP_02_MEDIA_CANDIDATOS_VAGAS_PUBLICAS '20180101','20200101'
SELECT * FROM AMBIENTE_DIMENSIONAL.DIM_OPORTUNIDADE

/* 
	- QUESTIONAMENTO 02
	- MEDIA DE CANDIDATOS POR OPORTUNIDADES PUBLICAS
*/
CREATE PROCEDURE SP_02_MEDIA_CANDIDATOS_VAGAS_PUBLICAS(@INICIO_PERIODO DATETIME, @FIM_PERIODO DATETIME)
AS
BEGIN
	SELECT AVG(FA.ID_OPORTUNIDADE) FROM AMBIENTE_DIMENSIONAL.FATO_ACOMPANHAMENTO FA
	INNER JOIN AMBIENTE_DIMENSIONAL.DIM_OPORTUNIDADE DO
	ON FA.ID_OPORTUNIDADE = DO.ID
	INNER JOIN AMBIENTE_DIMENSIONAL.DIM_TEMPO DT
	ON FA.ID_TEMPO = DT.ID
	WHERE EH_PUBLICA = 1 AND (DT.DATA >= @INICIO_PERIODO AND DT.DATA <= @FIM_PERIODO);
END

GO

/* 
	- QUESTIONAMENTO 04
	- QUANTIDADE DE SERVICOS CANCELADOS NO PERIODO
*/
CREATE PROCEDURE SP_04_SERVICO_CANCELADO_PERIODO(@INICIO_PERIODO DATETIME, @FIM_PERIODO DATETIME)
AS
BEGIN
	SELECT COUNT(FA.ID_SERVICO) FROM AMBIENTE_DIMENSIONAL.FATO_ACOMPANHAMENTO FA
	INNER JOIN AMBIENTE_DIMENSIONAL.DIM_SERVICO DS
	ON FA.ID_SERVICO = DS.ID
	INNER JOIN AMBIENTE_DIMENSIONAL.DIM_TEMPO DT
	ON FA.ID_TEMPO = DT.ID
	WHERE DS.STATUS = 'CANCELADA' AND (DT.DATA >= @INICIO_PERIODO AND DT.DATA <= @FIM_PERIODO);
END

GO

/* 
	- QUESTIONAMENTO 06
	- QUANTIDADE DE ACOMPANHAMENTOS PAGOS EM DINHEIRO
	- VALOR TOTAL DESSA QUANTIDADE.
*/
CREATE PROCEDURE SP_06_QTD_ESPECIE_TOTAL_VALOR(@INICIO_PERIODO DATETIME, @FIM_PERIODO DATETIME)
AS
BEGIN
	SELECT COUNT(FA.QTD) AS QUANTIDADE_ESPECIE, SUM(FA.VALOR) AS TOTAL FROM AMBIENTE_DIMENSIONAL.FATO_ACOMPANHAMENTO FA
	INNER JOIN AMBIENTE_DIMENSIONAL.DIM_TEMPO DT
	ON FA.ID_TEMPO = DT.ID
	WHERE (DT.DATA >= @INICIO_PERIODO AND DT.DATA <= @FIM_PERIODO);
END

GO

/* 
	- QUESTIONAMENTO 08
	- MEDIA DE VALORES DE ACOMPANHAMENTOS NO DIA
*/
CREATE PROCEDURE SP_08_MEDIA_ACOMPANHENTO_DIA(@DATA DATETIME)
AS
BEGIN
	SELECT AVG(FA.VALOR) FROM AMBIENTE_DIMENSIONAL.FATO_ACOMPANHAMENTO FA
	INNER JOIN AMBIENTE_DIMENSIONAL.DIM_TEMPO DT
	ON FA.ID_TEMPO = DT.ID
	WHERE DT.DATA = @DATA;
END

GO

/* 
	- QUESTIONAMENTO 14
	- NUMERO DE ACOMPANHAMENTOS POR CIDADE EM UM PERIODO DE TEMPO
*/
CREATE PROCEDURE SP_14_ACOMPANHAMENTOS_CIDADE(@CIDADE VARCHAR(45), @INICIO_PERIODO DATETIME, @FIM_PERIODO DATETIME)
AS
BEGIN
	SELECT COUNT(FA.ID_ACOMPANHANTE) FROM AMBIENTE_DIMENSIONAL.FATO_ACOMPANHAMENTO FA
	INNER JOIN AMBIENTE_DIMENSIONAL.DIM_ACOMPANHANTE DA
	ON FA.ID_ACOMPANHANTE = DA.ID
	INNER JOIN AMBIENTE_DIMENSIONAL.DIM_LOCALIDADE DL
	ON FA.ID_LOCALIDADE = DL.ID
	INNER JOIN AMBIENTE_DIMENSIONAL.DIM_TEMPO DT
	ON FA.ID_TEMPO = DT.ID
	WHERE DL.CIDADE = @CIDADE AND (DT.DATA >= @INICIO_PERIODO AND DT.DATA <= @FIM_PERIODO);
END

GO