/** 
 * UNIVERSIDADE FEDERAL DE SERGIPE 
 * DEPARTAMENTO DE SISTEMAS DE INFORMAÇÃO - DSI
 * SISTEMAS DE APOIO A DECISÃO -SAD
 * PROJETAR AMBIENTE DE SUPORTE A DECISÃO BASEADO EM SISTEMA DE ACOMPANHANTES
 * ABRAÃO ALVES E IGOR BRUNO
 * 30/07/2019
 **/
USE QueroAcompanhanteSAD

/* ------------------------------------------------------------------------------------------------------------ */


EXEC SP_OLTP_CARREGA_CLIENTES_E_ACOMPANHANTES '20190521'
EXEC SP_OLTP_CARGAS_SIMPLES '20190521'
EXEC SP_CARREGA_FATO '20190521'

SELECT * FROM TB_AUX_ACOMPANHANTE
SELECT * FROM TB_AUX_CLIENTE
SELECT * FROM TB_AUX_LOCALIDADE
SELECT * FROM TB_AUX_SERVICO
SELECT * FROM TB_AUX_TIPO_ACOMPANHAMENTO
SELECT * FROM TB_AUX_TRANSACAO
SELECT * FROM TB_AUX_OPORTUNIDADE
SELECT * FROM TB_AUX_FATO_ACOMPANHAMENTO

/* ------------------------------------------------------------------------------------------------------------ */


--- CARREGA DADOS DO AMBIENTE OPERACIONAL PARA AS TABELAS AUXILIARES DE CLIENTE E ACOMPANHANTE
CREATE PROCEDURE SP_OLTP_CARREGA_CLIENTES_E_ACOMPANHANTES (@DATACARGA DATETIME)
AS
	BEGIN
		DECLARE @IDUSUARIO INT
		DECLARE @NOME VARCHAR(45)
		DECLARE @CPF VARCHAR(11)
		DECLARE @TELEFONE VARCHAR(13)
		DECLARE @GENERO VARCHAR(45)
		DECLARE @USUARIO VARCHAR(45)
		DECLARE @NASCIMENTO DATE
		DECLARE @IDADE INT
		DECLARE @VALORHORA NUMERIC(10,2)

		DECLARE USUARIO CURSOR FOR 
		SELECT idUsuario, nome, cpf,telefone, genero, usuario, dataNascimento FROM Usuario

		DELETE FROM TB_AUX_CLIENTE WHERE data_carga = @DATACARGA
		DELETE FROM TB_AUX_ACOMPANHANTE WHERE data_carga = @DATACARGA	
		
		OPEN USUARIO
		FETCH USUARIO INTO @IDUSUARIO,@NOME,@CPF,@TELEFONE,@GENERO,@USUARIO,@NASCIMENTO

		WHILE (@@FETCH_STATUS = 0)
			BEGIN
				SET @IDADE = DATEDIFF(mm,@NASCIMENTO,@DATACARGA)/12

				IF (EXISTS (SELECT * FROM Acompanhante WHERE @IDUSUARIO = idAcompanhante))
					BEGIN
						SET @VALORHORA = (SELECT valorHora FROM Acompanhante WHERE @IDUSUARIO = idAcompanhante)

						INSERT INTO TB_AUX_ACOMPANHANTE (data_carga,codigo,nome,cpf,telefone,genero,usuario,data_nascimento,idade,valor_hora)
						VALUES(@DATACARGA,@IDUSUARIO,@NOME,@CPF,@TELEFONE,@GENERO,@USUARIO,@NASCIMENTO,@IDADE,@VALORHORA)
					END
				ELSE 
					BEGIN
						
						INSERT INTO TB_AUX_CLIENTE (data_carga,codigo,nome,cpf,telefone,genero,usuario,data_nascimento,idade)
						VALUES(@DATACARGA,@IDUSUARIO,@NOME,@CPF,@TELEFONE,@GENERO,@USUARIO,@NASCIMENTO,@IDADE)
					END
				FETCH USUARIO INTO @IDUSUARIO,@NOME,@CPF,@TELEFONE,@GENERO,@USUARIO,@NASCIMENTO
			END
			CLOSE USUARIO
			DEALLOCATE USUARIO
	END

GO
/* ------------------------------------------------------------------------------------------------------------ */

--- CARREGA DADOS DO AMBIENTE OPERACIONAL PARA AS TABELAS AUXILIARES DE ENDERECO, OPORTUNIDADE, SERVICO, TRANSACAO, TIPO DE ACOMPANHANMENTO
CREATE PROCEDURE SP_OLTP_CARGAS_SIMPLES (@DATACARGA DATETIME)
AS
	BEGIN
		
		DELETE FROM TB_AUX_OPORTUNIDADE WHERE data_carga = @DATACARGA
		DELETE FROM TB_AUX_SERVICO		WHERE data_carga = @DATACARGA
		DELETE FROM TB_AUX_TRANSACAO	WHERE data_carga = @DATACARGA	
		DELETE FROM TB_AUX_LOCALIDADE WHERE data_carga = @DATACARGA
		DELETE FROM TB_AUX_TIPO_ACOMPANHAMENTO WHERE data_carga = @DATACARGA

		INSERT INTO TB_AUX_LOCALIDADE (data_carga,codigo,estado,cidade,rua,bairro,id_servico)
		(SELECT @DATACARGA,idDetalhesEncontro,estado,cidade,rua,bairro,idServico FROM DetalhesEncontro)
	
		INSERT INTO TB_AUX_TRANSACAO (data_carga,codigo,id_servico,data_transacao)
		(SELECT @DATACARGA,idTransacao,idServico,dataEHora FROM Transacao)

		INSERT INTO TB_AUX_OPORTUNIDADE (data_carga, codigo, id_tipo_acompanhamento, id_cliente, id_servico,descricao,titulo,qtd_candidatos,status)
		(SELECT @DATACARGA,op.idOportunidade,op.idTipoAcompanhamento,op.idCliente,op.idServico,op.descricao,op.titulo,
			(SELECT COUNT(cd.idCandidatura) AS CANDIDATURA  FROM Candidatura as cd 
			Where cd.idOportunidade = op.idOportunidade GROUP BY cd.idOportunidade ), 
		status FROM Oportunidade as op)

		INSERT INTO TB_AUX_SERVICO(data_carga,codigo,data_solicitacao,id_acompanhante,id_cliente,id_tipo_acompanhamento,valor_total,status)
		(SELECT @DATACARGA,se.idServico,se.dataSolicitacao,se.idAcompanhante,se.idCliente,se.idTipoAcompanhamento,
			(SELECT dt.valor FROM DetalhesEncontro AS dt WHERE dt.idServico = se.idServico),
		status FROM Servico as se)

		INSERT INTO TB_AUX_TIPO_ACOMPANHAMENTO (data_carga,codigo,tipo_acompanhamento,descricao)
		(SELECT @DATACARGA,idTipoAcompanhamento,TipoAcompanhamento,descricao FROM TipoAcompanhamento)
	END


GO
/* ------------------------------------------------------------------------------------------------------------ */


--- CARREGA DADOS DAS TABELAS AUXILIARES PARA TABELA AUXILIAR DO FATO
ALTER PROCEDURE SP_CARREGA_FATO (@DATACARGA DATETIME)
AS
	BEGIN
		
		DECLARE @CODIGO INT
		DECLARE @DATASOLICITACAO DATETIME
		DECLARE @IDACOMPANHANTE INT
		DECLARE @IDCLIENTE INT
		DECLARE @IDTIPOACOMPANHAMENTO INT
		DECLARE @STATUS VARCHAR(50)
		DECLARE @IDTEMPO INT
		DECLARE @IDLOCALIDADE INT
		DECLARE @IDOPORTUNIDADE INT
		DECLARE @IDTRANSACAO INT
		DECLARE @IDFAIXAETARIAACOMPANHANTE INT
		DECLARE @IDFAIXAETARIACLEINTE INT
		DECLARE @IDADE INT
		DECLARE @IDTEMPOTRANSACAO INT
		DECLARE @VALOR NUMERIC(10,2)
		DECLARE @QTDCANDIDATOS INT

		DECLARE servico CURSOR FOR 
		SELECT codigo, data_solicitacao, id_acompanhante, 
			   id_cliente, id_tipo_acompanhamento,valor_total,status FROM TB_AUX_SERVICO
			   
		DELETE TB_AUX_FATO_ACOMPANHAMENTO WHERE @DATACARGA = data_carga

		OPEN servico
		FETCH servico INTO @CODIGO,@DATASOLICITACAO,@IDACOMPANHANTE,@IDCLIENTE,@IDTIPOACOMPANHAMENTO,@VALOR,@STATUS

		WHILE(@@FETCH_STATUS = 0)
			BEGIN
				
				SET @IDTEMPO			= (SELECT ID FROM DIM_TEMPO WHERE data = CAST(@DATACARGA AS DATE))
				SET @IDLOCALIDADE		= (SELECT codigo FROM TB_AUX_LOCALIDADE WHERE id_servico = @CODIGO)
				SET @IDOPORTUNIDADE		= (SELECT codigo FROM TB_AUX_OPORTUNIDADE WHERE id_servico = @CODIGO)
				SET @IDTRANSACAO		= (SELECT codigo FROM TB_AUX_TRANSACAO WHERE id_servico = @CODIGO)
				SET @IDADE				= (SELECT idade FROM TB_AUX_ACOMPANHANTE WHERE codigo = @IDACOMPANHANTE)
				SET @IDFAIXAETARIAACOMPANHANTE = (SELECT id FROM DIM_FAIXA_ETARIA WHERE @IDADE >= idade_inicial AND @IDADE <= idade_final)
				SET @IDADE					   = (SELECT idade FROM TB_AUX_CLIENTE WHERE codigo = @IDCLIENTE)
				SET @IDFAIXAETARIACLEINTE	   = (SELECT id FROM DIM_FAIXA_ETARIA WHERE @IDADE >= idade_inicial AND @IDADE <= idade_final)
				SET @IDTEMPOTRANSACAO		   = (SELECT id FROM DIM_TEMPO WHERE data = CAST((SELECT data_transacao FROM TB_AUX_TRANSACAO WHERE id_servico = @CODIGO) AS DATE))
				SET @QTDCANDIDATOS			   = (SELECT qtd_candidatos FROM TB_AUX_OPORTUNIDADE WHERE id_servico = @CODIGO)


				INSERT INTO TB_AUX_FATO_ACOMPANHAMENTO (data_carga,id_tempo,id_cliente,id_acompanhante,id_localidade,id_oportunidade,id_servico,id_transacao,id_faixa_etaria_cliente,id_faixa_etaria_acompanhante,id_data_transacao,id_tipo_acompanhamento,qtd,valor,qtd_candidatos)
				VALUES(@DATACARGA,@IDTEMPO,@IDCLIENTE,@IDACOMPANHANTE,@IDLOCALIDADE,@IDOPORTUNIDADE,@CODIGO,@IDTRANSACAO,@IDFAIXAETARIACLEINTE,@IDFAIXAETARIAACOMPANHANTE,@IDTEMPOTRANSACAO,@IDTIPOACOMPANHAMENTO,1,@VALOR,@QTDCANDIDATOS)

				FETCH servico INTO @CODIGO,@DATASOLICITACAO,@IDACOMPANHANTE,@IDCLIENTE,@IDTIPOACOMPANHAMENTO,@VALOR,@STATUS
			END
			CLOSE servico
			DEALLOCATE servico
	END